export enum AccessToken {
    AutoGenerate = 1
}

export const isAutoGeneratedToken = (accessToken?: string | AccessToken): accessToken is AccessToken.AutoGenerate => {
    return accessToken === AccessToken.AutoGenerate;
};

export interface RemoteLoggerServerParams {
    accessToken?: string | AccessToken;
}

export interface RemoteLoggerServer {
    listen: (callback: (data: RemoteLog) => void) => void;
}

export interface RemoteLog {
    data: unknown[];
    from?: string;
}