import * as express from 'express';
import * as cors from 'cors';
import {isAutoGeneratedToken, RemoteLog, RemoteLoggerServer, RemoteLoggerServerParams} from "./types";
import handlePostLog from "./controllers/handlePostLog";
import handleGetCheckRemoteLogger from "./controllers/handleGetCheckRemoteLogger";
import checkAccessToken from "./middleware/checkAccessToken";
import generateAccessToken from "./utils/generateAccessToken";
import {Subject} from "rxjs";

const remoteLoggerServer = (port: number, params?: RemoteLoggerServerParams): RemoteLoggerServer => {
    const accessToken = isAutoGeneratedToken(params?.accessToken) ? generateAccessToken() : params?.accessToken;
    if (isAutoGeneratedToken(params?.accessToken)) {
        console.log(`Access Token: ${accessToken}`);
    }

    const logSubject = new Subject<RemoteLog>();

    const app = express();
    app.use(express.json());
    app.use(cors());
    app.use(checkAccessToken(accessToken));

    app.get('/');
    app.get('/check_remote_logger', handleGetCheckRemoteLogger);
    app.post('/log', handlePostLog(logSubject));

    app.listen(port, () => {
        console.log(`Listening remote-logger-server on port ${port}`);
    });

    return {
        listen: (callback) => {
            logSubject.subscribe(value => {
                callback(value);
            });
        }
    };
};

export default remoteLoggerServer;